import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{
          display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
          padding: '32px 0 16px 0', background: 'linear-gradient(90deg, #0a0a0a 60%, #1a1a1a 100%)',
          color: '#ededed', marginBottom: 0
        }}>
          <Image
            src="/pro-pic.png"
            alt="Profile photo"
            width={120}
            height={120}
            style={{ borderRadius: '50%', border: '4px solid #2d8cff', boxShadow: '0 4px 24px #0008', objectFit: 'cover' }}
            priority
          />
          <h1 style={{ margin: '16px 0 4px 0', fontSize: 32, fontWeight: 700, letterSpacing: -1 }}>Joseph Billa</h1>
          <p style={{ fontSize: 18, color: '#8ecfff', marginBottom: 8 }}>Full-Stack Developer | FX, Stocks and Crypto Trader</p>
          <div style={{ display: 'flex', gap: 16, marginTop: 8 }}>
            <a href="https://github.com/Joe-Bills" target="_blank" rel="noopener noreferrer" title="GitHub" style={{ color: '#ededed', fontSize: 24 }}>
              <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M12 .5C5.73.5.5 5.73.5 12c0 5.08 3.29 9.39 7.86 10.91.58.11.79-.25.79-.56 0-.28-.01-1.02-.02-2-3.2.7-3.88-1.54-3.88-1.54-.53-1.34-1.3-1.7-1.3-1.7-1.06-.72.08-.71.08-.71 1.17.08 1.78 1.2 1.78 1.2 1.04 1.78 2.73 1.27 3.4.97.11-.75.41-1.27.74-1.56-2.55-.29-5.23-1.28-5.23-5.7 0-1.26.45-2.29 1.19-3.1-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.18 1.18a11.1 11.1 0 0 1 2.9-.39c.98 0 1.97.13 2.9.39 2.2-1.49 3.17-1.18 3.17-1.18.63 1.59.23 2.76.11 3.05.74.81 1.19 1.84 1.19 3.1 0 4.43-2.69 5.41-5.25 5.7.42.36.79 1.09.79 2.2 0 1.59-.01 2.87-.01 3.26 0 .31.21.68.8.56C20.71 21.39 24 17.08 24 12c0-6.27-5.23-11.5-12-11.5z"/></svg>
            </a>
            <a href="https://www.linkedin.com/in/joseph-billa-5a2726288/" target="_blank" rel="noopener noreferrer" title="LinkedIn" style={{ color: '#ededed', fontSize: 24 }}>
              <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M19 0h-14c-2.76 0-5 2.24-5 5v14c0 2.76 2.24 5 5 5h14c2.76 0 5-2.24 5-5v-14c0-2.76-2.24-5-5-5zm-11 19h-3v-9h3v9zm-1.5-10.28c-.97 0-1.75-.79-1.75-1.75s.78-1.75 1.75-1.75 1.75.79 1.75 1.75-.78 1.75-1.75 1.75zm13.5 10.28h-3v-4.5c0-1.08-.02-2.47-1.5-2.47-1.5 0-1.73 1.17-1.73 2.39v4.58h-3v-9h2.89v1.23h.04c.4-.75 1.38-1.54 2.84-1.54 3.04 0 3.6 2 3.6 4.59v4.72z"/></svg>
            </a>
          </div>
        </header>
        <nav style={{
          position: 'sticky', top: 0, zIndex: 100,
          background: '#181f2a', color: '#8ecfff',
          boxShadow: '0 2px 8px #0004',
          padding: '0',
          marginBottom: 32
        }}>
          <ul style={{ display: 'flex', gap: 32, listStyle: 'none', margin: 0, padding: '12px 0', justifyContent: 'center', fontSize: 18, fontWeight: 500 }}>
            <li><a href="/about" style={{ color: 'inherit' }}>About</a></li>
            <li><a href="/projects" style={{ color: 'inherit' }}>Projects</a></li>
            <li><a href="/contact" style={{ color: 'inherit' }}>Contact</a></li>
          </ul>
        </nav>
        <main style={{ minHeight: '60vh', width: '100%', maxWidth: 1100, margin: '0 auto', padding: '32px 16px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
